### ISSUE TITLE
tags filter reg ex

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [Jean-Baptiste-Lasselle/git-flowed-circleci#2]
* instead of : 

```Yaml
            tags:
              # only: /^v.*/
              only:
                - /^[0-999].[0-999].[0-999]/
                - /^[0-999].[0-999].[0-999]-alpha/
                - /^[0-999].[0-999].[0-999]-beta/
```

* use : 
```Yaml
            tags:
              # only: /^v.*/
              only:
                - /^[0-9]+.[0-9]+.[0-9]+/
                - /^[0-9]+.[0-9]+.[0-9]+-alpha/
                - /^[0-9]+.[0-9]+.[0-9]+-beta/
```
